---
name: Build on Push

on:
  push:                 # On push to any branch
  workflow_dispatch:    # Allow manual trigger

jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml
    with:
      version: 0.0.0-run.${{ github.run_number }}
